### ISSUE TITLE
Idk not wokring 

### ISSUE THREAD

**Issue by itsmechinmoy** [kaorlol/obtainium-artifact-downloader#1]
https://github.com/RepoDevil/Himitsu/releases
should show this in releases 
![image](https://github.com/kaorlol/obtainium-artifact-downloader/assets/167056923/ae128efb-5d28-4473-95a2-c1ea98e60eac)

but showing this in my repo
![image](https://github.com/kaorlol/obtainium-artifact-downloader/assets/167056923/6ad178e3-f916-4d1b-9d3b-9c9fc6f1fe95)

**Comment by kaorlol** [comment]
its because their .zip file included in the action only has one apk in it. Nothing i can do there.

**Comment by kaorlol** [comment]
ill look into it

**Comment by itsmechinmoy** [comment]
It's fixed
