### ISSUE TITLE
Ability to fetch apks from multiple repos?

### ISSUE THREAD

**Issue by itsmechinmoy** [kaorlol/obtainium-artifact-downloader#3]
can u check this https://github.com/itsmechinmoy/echo-extensions
ive added u as a collaborator , i want to get apks from 2 repos for now

**Comment by kaorlol** [comment]
Wait so do you want me to make it so you can add multiple repos to this? The only issue i saw with that was how would you seperate what apks to grab in obtainium.

**Comment by itsmechinmoy** [comment]
> Wait so do you want me to make it so you can add multiple repos to this? The only issue i saw with that was how would you seperate what apks to grab in obtainium.

that's the main issue

**Comment by itsmechinmoy** [comment]
https://chatgpt.com/share/052d6d66-edde-4ece-9512-11a6d8973fe5

**Comment by kaorlol** [comment]
> > Wait so do you want me to make it so you can add multiple repos to this? The only issue i saw with that was how would you seperate what apks to grab in obtainium.
> 
> that's the main issue 

Yeah you can add two of the same app

**Comment by itsmechinmoy** [comment]
> Yeah you cant add two of the same app

No any other ways to make it able to do it 😔?

**Comment by itsmechinmoy** [comment]
https://github.com/itsmechinmoy/echo-extensions
atleast check my repo even if obtainium cant differentiate it can it still release builds from multiple repos?
I've added u as a contributor
